zuul_server:
  gerrit_site: http://review.openstack.org
  git_origin: git://git.openstack.org
  gearman_host: 119.9.13.90
  gearman_port: 4730

debug_log: /var/log/turbo-hipster/debug.log
jobs_working_dir: /var/lib/turbo-hipster/jobs
git_working_dir: /var/lib/turbo-hipster/git
pip_download_cache: /var/cache/pip

plugins:
  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_devstack_131007
    function: build:real-db-upgrade_nova_mysql_devstack_131007

  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_devstack_150
    function: build:real-db-upgrade_nova_mysql_devstack_150

  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_trivial_500
    function: build:real-db-upgrade_nova_mysql_trivial_500

  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_trivial_6000
    function: build:real-db-upgrade_nova_mysql_trivial_6000

  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_user_001
    function: build:real-db-upgrade_nova_mysql_user_001

  - name: real_db_upgrade
    datasets_dir: /var/lib/turbo-hipster/datasets_user_002
    function: build:real-db-upgrade_nova_mysql_user_002

publish_logs:
  type: swift
  authurl: https://identity.api.rackspacecloud.com/v2.0/
  tenant: XXXX
  user: XXXXXX
  password: XXXXXX
  container: XXXXXX
  region: SYD
  prepend_url: http://www.rcbops.com/turbo_hipster/results/
